/// The environment variables SageFs reads are listed in docs/configuration.md, and that list is
/// not allowed to drift from the code. `SageFs.Core/Timeouts.fs` is where nearly all of them are
/// declared, so it is the source of truth for the set: every `SAGEFS_*` name it reads must be on
/// the page, and every `SAGEFS_*` name the page lists must be one the product actually reads
/// somewhere (a quoted literal in the code), so a variable that was renamed or deleted cannot
/// linger in the docs. Neither side holds a list of names here. Both are parsed from the files.
///
/// The page's tables are generated by `scripts/gen-configuration-doc.fsx`. When one of these
/// fails, run that script with the commit the links should point at, then edit the hand-written
/// part of the page for anything that is not a duration.
module SageFs.Tests.EnvVarDocTests

open System.IO
open System.Text.RegularExpressions
open Expecto
open Expecto.Flip

let private repoRoot = Path.GetFullPath(Path.Combine(__SOURCE_DIRECTORY__, ".."))

let private timeoutsSource = File.ReadAllLines(Path.Combine(repoRoot, "SageFs.Core", "Timeouts.fs"))
let private docText = File.ReadAllText(Path.Combine(repoRoot, "docs", "configuration.md"))

let private quotedVariable = Regex("\"(SAGEFS_[A-Z0-9_]+)\"", RegexOptions.Compiled)
let private backtickedVariable = Regex("`(SAGEFS_[A-Z0-9_]+)`", RegexOptions.Compiled)

let private isComment (line: string) = line.TrimStart().StartsWith "//"

/// Every `SAGEFS_*` name Timeouts.fs spells as a string literal, comments excluded.
let private declaredInTimeouts : Set<string> =
  timeoutsSource
  |> Array.filter (isComment >> not)
  |> Array.collect (fun line -> quotedVariable.Matches line |> Seq.map (fun m -> m.Groups.[1].Value) |> Seq.toArray)
  |> Set.ofArray

/// Every `SAGEFS_*` name the page puts in backticks.
let private namedInDoc : Set<string> =
  backtickedVariable.Matches docText |> Seq.map (fun m -> m.Groups.[1].Value) |> Set.ofSeq

/// Every `SAGEFS_*` name that appears as a string literal in any F# source the product or its agent hook ships.
let private literalsInProductSource : Set<string> =
  [ for project in [ "SageFs"; "SageFs.Core"; "SageFs.Host"; "tools" ] do
      let dir = Path.Combine(repoRoot, project)
      match Directory.Exists dir with
      | false -> ()
      | true ->
        for file in Directory.EnumerateFiles(dir, "*.fs", SearchOption.AllDirectories) do
          let relative = Path.GetRelativePath(repoRoot, file).Replace('\\', '/')
          match relative.Contains "/obj/" || relative.Contains "/bin/" with
          | true -> ()
          | false ->
            for line in File.ReadAllLines file do
              match isComment line with
              | true -> ()
              | false -> for m in quotedVariable.Matches line do yield m.Groups.[1].Value ]
  |> Set.ofList

/// `"VAR" <number>` on a Timeouts.fs line: the plain numeric default the code spells out next to the name.
let private numericDefaultsInSource : Map<string, float> =
  let pattern = Regex("\"(SAGEFS_[A-Z0-9_]+)\"\\s+([0-9_.]+)\\s*$", RegexOptions.Compiled)
  timeoutsSource
  |> Array.filter (isComment >> not)
  |> Array.choose (fun line ->
    let m = pattern.Match line
    match m.Success with
    | true -> Some (m.Groups.[1].Value, float (m.Groups.[2].Value.Replace("_", "")))
    | false -> None)
  |> Map.ofArray

/// The retention settings name their variable through a constant, so the default sits on a different line.
let private numericRetentionDefaults : Map<string, float> =
  let nameOf = Regex("^\\s*let\\s+(\\w+EnvVar)\\s*=\\s*\"(SAGEFS_[A-Z0-9_]+)\"", RegexOptions.Compiled)
  let reader = Regex("^\\s*let\\s+\\w+\\s*=\\s*envOrDefault(?:Days|Int)\\s+(\\w+EnvVar)\\s+([0-9_.]+)\\s*$", RegexOptions.Compiled)
  let names =
    timeoutsSource
    |> Array.choose (fun line ->
      let m = nameOf.Match line
      match m.Success with
      | true -> Some (m.Groups.[1].Value, m.Groups.[2].Value)
      | false -> None)
    |> Map.ofArray
  timeoutsSource
  |> Array.choose (fun line ->
    let m = reader.Match line
    match m.Success with
    | false -> None
    | true ->
      match Map.tryFind m.Groups.[1].Value names with
      | Some variable -> Some (variable, float (m.Groups.[2].Value.Replace("_", "")))
      | None -> None)
  |> Map.ofArray

/// `| `VAR` | <default> | ...` rows of the page's tables.
let private defaultsInDoc : Map<string, string> =
  let row = Regex("^\\|\\s*`(SAGEFS_[A-Z0-9_]+)`\\s*\\|\\s*([0-9.]+)\\s*\\|", RegexOptions.Compiled ||| RegexOptions.Multiline)
  row.Matches docText
  |> Seq.map (fun m -> m.Groups.[1].Value, m.Groups.[2].Value)
  |> Map.ofSeq

[<Tests>]
let tests =
  testList "Environment variable docs" [

    testCase "WHY — the parse found the variables, so an empty comparison below cannot pass by finding nothing on either side" <| fun _ ->
      declaredInTimeouts |> Set.isEmpty |> Expect.isFalse "Timeouts.fs yields variable names"
      namedInDoc |> Set.isEmpty |> Expect.isFalse "docs/configuration.md names variables"
      literalsInProductSource |> Set.isEmpty |> Expect.isFalse "the product source yields variable names"

    testCase "WHY — every variable Timeouts.fs reads is on the configuration page, so an operator can find the one that is hanging their warmup" <| fun _ ->
      let missing = Set.difference declaredInTimeouts namedInDoc |> Set.toList
      missing |> Expect.isEmpty "each variable in Timeouts.fs is named on docs/configuration.md (run scripts/gen-configuration-doc.fsx)"

    testCase "WHY — every variable the configuration page names is one the product reads, so a renamed or deleted variable does not stay documented" <| fun _ ->
      let unknown = Set.difference namedInDoc literalsInProductSource |> Set.toList
      unknown |> Expect.isEmpty "each variable on docs/configuration.md is a string literal somewhere in SageFs, SageFs.Core, SageFs.Host or tools"

    testCase "WHY — a default on the page is the default in the code, so tuning from the page starts from the real number" <| fun _ ->
      let inCode = Map.fold (fun acc k v -> Map.add k v acc) numericDefaultsInSource numericRetentionDefaults
      let wrong =
        defaultsInDoc
        |> Map.toList
        |> List.choose (fun (name, shown) ->
          match Map.tryFind name inCode with
          | None -> None
          | Some expected ->
            match float shown = expected with
            | true -> None
            | false -> Some (sprintf "%s: page says %s, code says %g" name shown expected))
      wrong |> Expect.isEmpty "every default on the page matches the plain numeric default in Timeouts.fs"
      let checkedCount = defaultsInDoc |> Map.toList |> List.filter (fun (name, _) -> Map.containsKey name inCode) |> List.length
      checkedCount > 0 |> Expect.isTrue "at least one default on the page was compared with the code"
  ]
