/// The pure retention decisions for friction.db and cohort.ledger.db
/// (`LocalDataRetention`). The SQLite side is covered in
/// `LocalDataSqliteTests`, and months of seeded use in `RetentionSimDstTests`.
module SageFs.Tests.LocalDataRetentionTests

open System
open Expecto
open Expecto.Flip
open SageFs.Cohort
open SageFs.Features.LocalDataRetention

let private now = DateTimeOffset(2026, 9, 22, 12, 0, 0, TimeSpan.Zero)
let private versions = [| "0.6.1"; "0.6.2"; "0.6.3" |]
let private current = versions.[0]

/// A row built from generated bytes: which version, how many hours old, and
/// which kind.
let private rowOf (i: int) (versionByte: byte, ageHours: byte, kindByte: byte) : RetainedRow =
  { Id = int64 i
    OccurredAt = now.AddHours(-(float ageHours) * 3.0)
    Version = versions.[int versionByte % versions.Length]
    Kind = sprintf "tool%d/CompletedCleanly" (int kindByte % 4) }

let private rowsOf (raw: (byte * byte * byte) list) = raw |> List.mapi rowOf

let private policyOf (maxRows: byte) : FrictionPolicy =
  { MaxAge = SageFs.DataRetention.frictionMaxAge; MaxRows = int maxRows % 60; MaxAggregateVersions = 2 }

let private ids (rows: RetainedRow list) = rows |> List.map (fun r -> r.Id) |> Set.ofList

let private mkEntry (seq: int64) (clock: DateTime) (state: CohortState<string>) (command: CohortCommand<string>) =
  match SageFs.Cohort.decide clock [| byte seq |] state command with
  | Ok(next, events, _) ->
    next, ({ Seq = LanguagePrimitives.Int64WithMeasure seq; Clock = clock; Entropy = [| byte seq |]; Command = command; Events = events } : LedgerEntry<string>)
  | Error e -> failtestf "cohort command refused: %A" e

[<Tests>]
let localDataRetentionTests =
  testList "Local data retention" [

    testProperty "after a prune only the running version's rows are left, inside the age and row caps" <|
      fun (raw: (byte * byte * byte) list) (maxRows: byte) ->
        let policy = policyOf maxRows
        let decision = decide policy now current (rowsOf raw)
        decision.Kept.Length <= policy.MaxRows
        && decision.Kept |> List.forall (fun r -> r.Version = current && now - r.OccurredAt <= policy.MaxAge)

    testProperty "the newest running-version rows inside the window are never dropped" <|
      fun (raw: (byte * byte * byte) list) (maxRows: byte) ->
        let policy = policyOf maxRows
        let rows = rowsOf raw
        let mustSurvive =
          rows
          |> List.filter (fun r -> r.Version = current && now - r.OccurredAt <= policy.MaxAge)
          |> List.sortByDescending (fun r -> r.OccurredAt, r.Id)
          |> List.truncate policy.MaxRows
        let decision = decide policy now current rows
        Set.isSubset (ids mustSurvive) (ids decision.Kept)

    testProperty "every row is either kept or dropped, never both, never neither" <|
      fun (raw: (byte * byte * byte) list) (maxRows: byte) ->
        let rows = rowsOf raw
        let decision = decide (policyOf maxRows) now current rows
        let dropped = decision.Dropped |> List.map fst
        Set.intersect (ids decision.Kept) (ids dropped) |> Set.isEmpty
        && Set.union (ids decision.Kept) (ids dropped) = ids rows

    testProperty "every dropped row is counted once in its version's aggregate" <|
      fun (raw: (byte * byte * byte) list) (maxRows: byte) ->
        let decision = decide (policyOf maxRows) now current (rowsOf raw)
        let expected =
          decision.Dropped
          |> List.countBy (fun (r, _) -> ({ Version = r.Version; Kind = r.Kind } : AggregateKey))
          |> Map.ofList
        decision.Aggregated = expected

    testProperty "a prune is idempotent: pruning what's left drops nothing" <|
      fun (raw: (byte * byte * byte) list) (maxRows: byte) ->
        let policy = policyOf maxRows
        let once = decide policy now current (rowsOf raw)
        let twice = decide policy now current once.Kept
        twice.Dropped |> List.isEmpty

    testCase "a row from another version goes even when it's brand new" <| fun _ ->
      let fresh = { Id = 1L; OccurredAt = now; Version = "0.6.2"; Kind = "t/CompletedCleanly" }
      let decision = decide (policyOf 10uy) now current [ fresh ]
      decision.Dropped |> Expect.equal "the other version's row is rolled up" [ fresh, DropReason.OtherVersion ]

    testCase "the age-only twin keeps another version's fresh rows, which is the bug it witnesses" <| fun _ ->
      let fresh = { Id = 1L; OccurredAt = now; Version = "0.6.2"; Kind = "t/CompletedCleanly" }
      let decision = decideByAgeOnlyTwin (policyOf 10uy) now current [ fresh ]
      decision.Kept |> Expect.equal "the twin keeps it" [ fresh ]

    testProperty "at most MaxAggregateVersions versions keep aggregates, the most recently seen ones" <|
      fun (seen: (byte * byte) list) ->
        let policy = { MaxAge = SageFs.DataRetention.frictionMaxAge; MaxRows = 10; MaxAggregateVersions = 3 }
        let lastSeen =
          seen
          |> List.map (fun (v, hoursAgo) -> sprintf "0.5.%d" (int v % 8), now.AddHours(-(float hoursAgo)))
          |> List.groupBy fst
          |> List.map (fun (v, xs) -> v, xs |> List.map snd |> List.max)
          |> Map.ofList
        let dropped = aggregateVersionsToDrop policy "0.5.0" lastSeen |> Set.ofList
        let kept = lastSeen |> Map.filter (fun v _ -> not (Set.contains v dropped))
        let newestDropped = dropped |> Seq.map (fun v -> lastSeen.[v]) |> Seq.fold max DateTimeOffset.MinValue
        kept.Count <= policy.MaxAggregateVersions
        && not (Set.contains "0.5.0" dropped)
        && kept |> Map.forall (fun v seenAt -> v = "0.5.0" || seenAt >= newestDropped)

    testList "the cohort ledger" [
      let t0 = DateTime(2026, 9, 1, 0, 0, 0, DateTimeKind.Utc)
      let retention = SageFs.DataRetention.cohortLedgerRetention
      // The cohort is opened by `CohortState.empty`, which is Machine-scoped — the
      // v1 shape. Both ledger rows below are written into that one cohort.
      let machine = SageFs.CohortScope.Machine
      let joined, joinEntry = mkEntry 0L t0 (CohortState.empty ()) (CohortCommand.Join("ada", JoinableRole.Implementer, None, machine))
      let _, departEntry = mkEntry 1L (t0.AddHours 1.0) joined (CohortCommand.Depart("ada", machine))

      testCase "an empty ledger has nothing to do" <| fun _ ->
        // The scope is named, not inferred: a store holding several cohorts has to be told which
        // one it is being asked about, because the rows it deletes are that scope's and no other's.
        decideLedger retention (t0.AddDays 30.0) machine ([]: LedgerEntry<string> list)
        |> Expect.equal "nothing stored, and the scope it says so about is named" (LedgerDecision.Kept(machine, CohortActivity.Finished))

      testCase "a running cohort is never cleared, however old its rows are" <| fun _ ->
        decideLedger retention (t0.AddDays 365.0) machine [ joinEntry ]
        |> Expect.equal "kept" (LedgerDecision.Kept(machine, CohortActivity.Active(1, 0, 0)))

      testCase "a finished cohort inside the window is kept" <| fun _ ->
        decideLedger retention (t0.AddDays 2.0) machine [ joinEntry; departEntry ]
        |> Expect.equal "kept" (LedgerDecision.KeptRecent(machine, departEntry.Clock))

      testCase "a finished cohort past the window is cleared" <| fun _ ->
        decideLedger retention (t0.AddDays 30.0) machine [ joinEntry; departEntry ]
        |> Expect.equal "cleared" (LedgerDecision.Cleared(machine, departEntry.Clock, 2))

      testCase "the decision is about the scope it is asked about, not the scope some other ledger's rows carry" <| fun _ ->
        // The pure counterpart of the SQLite sweep's regression. Retention is a property of ONE
        // cohort finishing, so two cohorts in two scopes are two questions, and `decideLedger`
        // answers each one from its own scope's rows alone. Both histories below are REAL histories
        // of their own scope (`CohortState.forScope`), because a history is only replayable by the
        // scope it belongs to: fold a machine-scoped history as a repo cohort and `decide` refuses
        // every command as `WrongCohortScope`, which is a refusal to say anything at all rather than
        // a verdict about that repo.
        let repo = SageFs.CohortScope.Repository "/tmp/sagefs-decide-ledger-scope"
        let other = SageFs.CohortScope.Repository "/tmp/sagefs-decide-ledger-other"
        let repoJoin, repoJoinEntry = mkEntry 0L t0 (CohortState.forScope repo) (CohortCommand.Join("ada", JoinableRole.Implementer, None, repo))
        let _, repoDepartEntry = mkEntry 1L (t0.AddHours 1.0) repoJoin (CohortCommand.Depart("ada", repo))
        let otherJoin, otherJoinEntry = mkEntry 0L t0 (CohortState.forScope other) (CohortCommand.Join("bo", JoinableRole.Implementer, None, other))

        decideLedger retention (t0.AddDays 30.0) repo [ repoJoinEntry; repoDepartEntry ]
        |> Expect.equal "a finished cohort's own rows clear that scope"
             (LedgerDecision.Cleared(repo, repoDepartEntry.Clock, 2))
        decideLedger retention (t0.AddDays 365.0) other [ otherJoinEntry ]
        |> Expect.equal "and the same function leaves another scope's live cohort alone"
             (LedgerDecision.Kept(other, CohortActivity.Active(1, 0, 0)))
        // And the two are judged independently of one another: the repo cohort's departure cannot
        // make the other scope read as finished, and the other scope's presence cannot keep the repo
        // scope's rows alive. Folding both scopes into one replay could only have produced one of
        // these two answers.
        decideLedger retention (t0.AddDays 30.0) repo [ repoJoinEntry; repoDepartEntry; otherJoinEntry ]
        |> Expect.equal "another scope's rows cannot make a finished cohort look active"
             (LedgerDecision.Cleared(repo, repoJoinEntry.Clock, 3))
    ]
  ]
