<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <GenerateProgramFile>false</GenerateProgramFile>
        <LangVersion>preview</LangVersion>
        <NoWarn>$(NoWarn);FS3511</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="TestInfrastructure.fs" />
        <Compile Include="SageFsConfigTests.fs" />
        <Compile Include="AppStateCustomTests.fs" />
        <Compile Include="DaemonModeProxyTests.fs" />
        <Compile Include="FalcoTests.fs" />
        <Compile Include="PushEventTests.fs" />
        <Compile Include="McpAdapterTests.fs" />
        <Compile Include="McpServerE2ETests.fs" />
        <Compile Include="McpServerIntegrationTests.fs" />
        <Compile Include="McpLlmInteropTests.fs" />
        <Compile Include="SharedSageFsFixture.fs" />
        <Compile Include="SharedGenerators.fs" />
        <Compile Include="McpFormatterPropertyTests.fs" />
        <Compile Include="CompExprSimplifierTests.fs" />
        <Compile Include="MethodPatcherTests.fs" />
        <Compile Include="SnapshotTests.fs" />
        <Compile Include="ToolDescriptionTests.fs" />
        <Compile Include="SessionResetTests.fs" />
        <Compile Include="ShadowCopyTests.fs" />
        <Compile Include="StandbyPoolTests.fs" />
        <Compile Include="DiagnosticsToolTests.fs" />
        <Compile Include="DiagnosticsStoreTests.fs" />
        <Compile Include="ActorCreationTests.fs" />
        <Compile Include="ActorEventEmissionTests.fs" />
        <Compile Include="EvalCancellationTests.fs" />
        <Compile Include="ActorSplitTests.fs" />
        <Compile Include="AffordanceTests.fs" />
        <Compile Include="AffordancesPropertyTests.fs" />
        <Compile Include="WorkerProtocolTests.fs" />
        <Compile Include="DaemonStateTests.fs" />
        <Compile Include="DaemonIntegrationTests.fs" />
        <Compile Include="SessionOperationsTests.fs" />
        <Compile Include="RestartPolicyTests.fs" />
        <Compile Include="ResilientActorTests.fs" />
        <Compile Include="WatchdogTests.fs" />
        <Compile Include="FileWatcherTests.fs" />
        <Compile Include="EditorTests.fs" />
        <Compile Include="SessionDisplayTests.fs" />
        <Compile Include="SageFsEventTests.fs" />
        <Compile Include="SageFsAppTests.fs" />
        <Compile Include="SageFsUpdatePropertyTests.fs" />
        <Compile Include="SageFsEffectHandlerTests.fs" />
        <Compile Include="ElmLoopResilienceTests.fs" />
        <Compile Include="ElmLoopMsgLabelTests.fs" />
        <Compile Include="ElmLoopStateMachineTests.fs" />
        <Compile Include="DashboardParsingTests.fs" />
        <Compile Include="DirectoryConfigTests.fs" />
        <Compile Include="ConnectionTrackerTests.fs" />
        <Compile Include="TerminalUITests.fs" />
        <Compile Include="CellGridTests.fs" />
        <Compile Include="ScreenTests.fs" />
        <Compile Include="DashboardSnapshotTests.fs" />
        <Compile Include="TuiClientTests.fs" />
        <Compile Include="MultiUiConsistencyTests.fs" />
        <Compile Include="TuiGuiSharedTests.fs" />
        <Compile Include="ThemePersistenceTests.fs" />
        <Compile Include="DashboardBrowserTests.fs" />
        <Compile Include="ElmDaemonTests.fs" />
        <Compile Include="SessionCreationTests.fs" />
        <Compile Include="SessionCreationUxTests.fs" />
        <Compile Include="ExplorationTests.fs" />
        <Compile Include="ReplayTests.fs" />
        <Compile Include="HotReloadTests.fs" />
        <Compile Include="HotReloadStateTests.fs" />
        <Compile Include="HotReloadBrowserTests.fs" />
        <Compile Include="HotReloadEndpointTests.fs" />
        <Compile Include="DevReloadTests.fs" />
        <Compile Include="WorkerHttpTransportTests.fs" />
        <Compile Include="SessionIsolationTests.fs" />
        <Compile Include="CleanStdoutTests.fs" />
        <Compile Include="DiffEmitTests.fs" />
        <Compile Include="SyntaxHighlightTests.fs" />
        <Compile Include="VtInputParserTests.fs" />
        <Compile Include="PluginContractTests.fs" />
        <Compile Include="ProjectLoadingTests.fs" />
        <Compile Include="McpWireProtocolTests.fs" />
        <Compile Include="HttpApiIntegrationTests.fs" />
        <Compile Include="WarmupContextTests.fs" />
        <Compile Include="VscodeExtensionTests.fs" />
        <Compile Include="LiveTestingTestHelpers.fs" />
        <Compile Include="LiveTestingCoreTests.fs" />
        <Compile Include="LiveTestingCycleTests.fs" />
        <Compile Include="LiveTestingCoverageTests.fs" />
        <Compile Include="LiveTestingElmTests.fs" />
        <Compile Include="LiveTestingGraphTests.fs" />
        <Compile Include="DomainModelVizTests.fs" />
        <Compile Include="LiveTestingExecutorTests.fs" />
        <Compile Include="ArgsCleanupTests.fs" />
        <Compile Include="AssemblyResolverTests.fs" />
        <Compile Include="SseWriterTests.fs" />
        <Compile Include="SseDedupKeyTests.fs" />
        <Compile Include="ThemeTests.fs" />
        <Compile Include="ErrorMessagesTests.fs" />
        <Compile Include="RetryPolicyTests.fs" />
        <Compile Include="FsiRewriteTests.fs" />
        <Compile Include="LiveTestingTypesTests.fs" />
        <Compile Include="SessionPredicatesAndUiTests.fs" />
        <Compile Include="SessionManagerCqrsTests.fs" />
        <Compile Include="AutoCompletionAndEventsTests.fs" />
        <Compile Include="DrawAndRectPrimitivesTests.fs" />
        <Compile Include="ThemesGutterAndDiagnosticsTests.fs" />
        <Compile Include="InstrumentationTests.fs" />
        <Compile Include="McpToolAuditTests.fs" />
        <Compile Include="FeatureParityTests.fs" />
        <Compile Include="LayoutAndInputTests.fs" />
        <Compile Include="PureModulesComprehensiveTests.fs" />
        <Compile Include="CoverageInstrumenterTests.fs" />
        <Compile Include="EvalDedupTests.fs" />
        <Compile Include="EvalDiffTests.fs" />
        <Compile Include="CellDependencyGraphTests.fs" />
        <Compile Include="BindingExplorerTests.fs" />
        <Compile Include="EvalTimelineTests.fs" />
        <Compile Include="NotebookExportTests.fs" />
        <Compile Include="SseFeatureFormatTests.fs" />
        <Compile Include="DomainModelSseTests.fs" />
        <Compile Include="FeatureHookTests.fs" />
        <Compile Include="AlgebraicPropertyTests.fs" />
        <Compile Include="EventFoldPropertyTests.fs" />
        <Compile Include="BinaryFormatTests.fs" />
        <Compile Include="ManifestPersistenceTests.fs" />
        <Compile Include="PersistenceComplianceTests.fs" />
        <Compile Include="McpStateHandlerTests.fs" />
        <Compile Include="CompilationContextTests.fs" />
        <Compile Include="SageFsErrorClassificationTests.fs" />
        <Compile Include="SageFsErrorPropertyTests.fs" />
        <Compile Include="ResultCeTests.fs" />
        <Compile Include="SessionIdTests.fs" />
        <Compile Include="EndpointContractTests.fs" />
        <Compile Include="FsiRegressionTests.fs" />
        <Compile Include="HotReloadingPropertyTests.fs" />
        <Compile Include="DevReloadMiddlewareTests.fs" />
        <Compile Include="QuarantineTests.fs" />
        <Compile Include="FlakyClassificationTests.fs" />
        <Compile Include="FlakyClassificationPropertyTests.fs" />
        <Compile Include="Tier0CorrectnessTests.fs" />
        <Compile Include="FileCoverageTests.fs" />
        <Compile Include="TestRunExplainerTests.fs" />
        <Compile Include="BatchFlusherTests.fs" />
        <Compile Include="BatchFlusherPropertyTests.fs" />
        <Compile Include="LifecyclePropertyTests.fs" />
        <Compile Include="Benchmarks.fs" />
        <Compile Include="FsiCrossSubmissionTests.fs" />
        <Compile Include="Round4HardeningTests.fs" />
        <Compile Include="Round5HardeningTests.fs" />
        <Compile Include="Round6HardeningTests.fs" />
        <Compile Include="Round7HardeningTests.fs" />
        <Compile Include="Round8HardeningTests.fs" />
        <Compile Include="Round9HardeningTests.fs" />
        <Compile Include="Round10HardeningTests.fs" />
        <Compile Include="Round11HardeningTests.fs" />
        <Compile Include="Round12HardeningTests.fs" />
        <Compile Include="Round13HardeningTests.fs" />
        <Compile Include="Round14HardeningTests.fs" />
        <Compile Include="Round15HardeningTests.fs" />
        <Compile Include="StructAuditTests.fs" />
        <Compile Include="MeasureTests.fs" />
        <Compile Include="CellGridMonoidTests.fs" />
        <Compile Include="MealyEquivalenceTests.fs" />
        <Compile Include="EvalPipelineTests.fs" />
        <Compile Include="RingBufferTests.fs" />
        <Compile Include="ModelSnapshotTests.fs" />
        <Compile Include="TimeTravelTests.fs" />
        <Compile Include="JupyterKernelTests.fs" />
        <Compile Include="TracingMiddlewareTests.fs" />
        <Compile Include="ResultExTests.fs" />
        <Compile Include="RenderInstrumentationTests.fs" />
        <Compile Include="EventExhaustivenessTests.fs" />
        <Compile Include="ComplianceSuite.fs" />
        <Compile Include="AppStatePropertyTests.fs" />
        <Compile Include="EditorPropertyTests.fs" />
        <Compile Include="ArchitectureTests.fs" />
        <Compile Include="TestStatusVocabularyTests.fs" />
        <Compile Include="HotReloadVisibilityTests.fs" />
        <Compile Include="TutorialTests.fs" />
        <Compile Include="UiDensityTests.fs" />
        <Compile Include="SmartResetTests.fs" />
        <Compile Include="EvalProvenanceTests.fs" />
        <Compile Include="PipelineFlameTests.fs" />
        <Compile Include="SessionScribeTests.fs" />
        <Compile Include="MessageJournalTests.fs" />
        <Compile Include="TestNarrationTests.fs" />
        <Compile Include="DaemonHealthTests.fs" />
        <Compile Include="ScratchPadTests.fs" />
        <Compile Include="EvalRippleTests.fs" />
        <Compile Include="EvalLensTests.fs" />
        <Compile Include="WhatIfTests.fs" />
        <Compile Include="GhostwriterTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
        <PackageReference Include="Expecto" />
        <PackageReference Include="Expecto.FsCheck" />
        <PackageReference Include="Expecto.Hopac" />
        <PackageReference Include="FsCheck" />
        <PackageReference Include="YoloDev.Expecto.TestSdk" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Lib.Harmony" />
        <PackageReference Include="Fantomas.Core" />
        <PackageReference Include="Falco" />
        <PackageReference Include="Falco.Markup" />
        <PackageReference Include="FSharp.SystemTextJson" />
        <PackageReference Include="Verify.Expecto" />
        <PackageReference Include="Microsoft.Playwright" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="snapshots\**\*.verified.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SageFs.Core\SageFs.Core.fsproj" />
        <ProjectReference Include="..\SageFs\SageFs.fsproj" />
    </ItemGroup>

</Project>
