/// Coverage for `TweakTransaction`: a pure state machine over
/// parse/type-check/evaluate/apply/journal, fed arbitrary, including
/// out-of-order and adversarial, event sequences via FsCheck, proving the
/// three invariants the spec asks for hold no matter what arrives.
module SageFs.Tests.TweakTransactionTests

open Expecto
open Expecto.Flip
open FsCheck
open FsCheck.FSharp
open SageFs.Features.Tweak.TweakTransaction

// A small closed alphabet of events over `int` values, generated by FsCheck,
// deliberately including events that make no sense for whatever state comes
// before them, since the point is to prove `step` is total and safe under
// garbage, not just under the happy path.
let private genEvent : Gen<TweakEvent<int>> =
  Gen.oneof [
    Gen.map TweakEvent.Started (Gen.elements [ "1"; "2"; "gravity * 2" ])
    Gen.constant TweakEvent.Parsed
    Gen.map TweakEvent.ParseFailed (Gen.elements [ "bad syntax" ])
    Gen.constant TweakEvent.TypeChecked
    Gen.map TweakEvent.TypeCheckFailed (Gen.elements [ "wrong type" ])
    Gen.map TweakEvent.Evaluated (Gen.choose (0, 100))
    Gen.map TweakEvent.EvaluateFailed (Gen.elements [ "threw" ])
    Gen.constant TweakEvent.Applied
    Gen.map TweakEvent.ApplyFailed (Gen.elements [ "apply threw" ])
    Gen.constant TweakEvent.Journaled
    Gen.map TweakEvent.JournalFailed (Gen.elements [ "disk full" ])
  ]

type private EventGenerators =
  static member Event() : Arbitrary<TweakEvent<int>> = Arb.fromGen genEvent

let private cfg = { FsCheckConfig.defaultConfig with arbitrary = [ typeof<EventGenerators> ]; maxTest = 300 }

/// Every state a fold ever passes through, oldest first (including the
/// initial state), so an invariant can look at consecutive pairs.
let private trace (events: TweakEvent<int> list) : TweakState<int> list =
  events |> List.scan step (initial 0)

[<Tests>]
let tweakTransactionTests =
  testList "TweakTransaction" [

    testCase "the happy path reaches Journaled with the new value live" <| fun _ ->
      let final =
        run 0 [ TweakEvent.Started "1"; TweakEvent.Parsed; TweakEvent.TypeChecked
                TweakEvent.Evaluated 42; TweakEvent.Applied; TweakEvent.Journaled ]
      final |> Expect.equal "reaches Journaled with the evaluated value" (TweakState.Journaled(42, "1"))

    testCase "a failure at any step keeps the last good value" <| fun _ ->
      let afterOneGoodTweak = run 0 [ TweakEvent.Started "1"; TweakEvent.Parsed; TweakEvent.TypeChecked; TweakEvent.Evaluated 5; TweakEvent.Applied; TweakEvent.Journaled ]
      liveOf afterOneGoodTweak |> Expect.equal "live is 5 after the first tweak" 5
      let afterFailedSecond =
        [ TweakEvent.Started "2"; TweakEvent.Parsed; TweakEvent.TypeChecked; TweakEvent.EvaluateFailed "boom" ]
        |> List.fold step afterOneGoodTweak
      liveOf afterFailedSecond |> Expect.equal "a failed second tweak keeps the first tweak's value" 5
      isFailed afterFailedSecond |> Expect.isTrue "and the state says so"

    testCase "a journal failure still keeps the value that was applied" <| fun _ ->
      let final = run 0 [ TweakEvent.Started "1"; TweakEvent.Parsed; TweakEvent.TypeChecked; TweakEvent.Evaluated 9; TweakEvent.Applied; TweakEvent.JournalFailed "disk full" ]
      liveOf final |> Expect.equal "apply already landed; only durability failed" 9

    testCase "an event out of order fails safely rather than corrupting state" <| fun _ ->
      let final = run 0 [ TweakEvent.Applied ]
      isFailed final |> Expect.isTrue "Applied with nothing evaluated is rejected"
      liveOf final |> Expect.equal "the original live value is untouched" 0

    testCase "a fresh Started always wins, discarding whatever was mid-flight" <| fun _ ->
      let final = run 0 [ TweakEvent.Started "1"; TweakEvent.Parsed; TweakEvent.Started "2" ]
      final |> Expect.equal "the newest attempt replaces the old one" (TweakState.Parsing(0, "2"))

    testPropertyWithConfig cfg "NEVER-APPLIED-WITHOUT-TYPE-CHECK, Applied only ever follows Evaluated" <|
      fun (events: TweakEvent<int> list) ->
        trace events
        |> List.pairwise
        |> List.forall (fun (before, after) ->
          match after with
          | TweakState.Applied _ ->
            match before with
            | TweakState.Evaluated _ -> true
            | _ -> false
          | _ -> true)

    testPropertyWithConfig cfg "FAILURE-KEEPS-LAST-GOOD, live never changes across a transition into Failed" <|
      fun (events: TweakEvent<int> list) ->
        trace events
        |> List.pairwise
        |> List.forall (fun (before, after) ->
          match after with
          | TweakState.Failed(live, _, _) -> live = liveOf before
          | _ -> true)

    testPropertyWithConfig cfg "JOURNALED-ONLY-AFTER-APPLIED, Journaled only ever follows Applied" <|
      fun (events: TweakEvent<int> list) ->
        trace events
        |> List.pairwise
        |> List.forall (fun (before, after) ->
          match after with
          | TweakState.Journaled _ ->
            match before with
            | TweakState.Applied _ -> true
            | _ -> false
          | _ -> true)

    testPropertyWithConfig cfg "TOTAL, step never throws, for any event against any state" <|
      fun (events: TweakEvent<int> list) ->
        try
          trace events |> ignore
          true
        with _ -> false
  ]
