<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Falco" />
    <PackageReference Include="Falco.Markup" />
    <PackageReference Include="Falco.Datastar" />
  </ItemGroup>

</Project>
