module SageFs.Features.SessionScribe

open SageFs.Features.CellDependencyGraph

/// A cleaned-up entry for script export.
type ScribeEntry = {
  CellId: CellId
  Code: string
  Bindings: string list
  Dependencies: CellId list
}

module SessionScribe =

  /// Keep only the latest version of each cell (by CellId).
  let dedup (entries: ScribeEntry list) : ScribeEntry list =
    entries
    |> List.rev
    |> List.distinctBy (fun e -> e.CellId)
    |> List.rev

  /// Topological sort: dependencies come before dependents.
  /// Falls back to original order for independent cells.
  let toposort (entries: ScribeEntry list) : ScribeEntry list =
    match entries with
    | [] -> []
    | _ ->
      let byId = entries |> List.map (fun e -> (e.CellId, e)) |> Map.ofList
      let allIds = entries |> List.map (fun e -> e.CellId) |> Set.ofList
      let rec visit (visited: Set<CellId>) (result: ScribeEntry list) (id: CellId) =
        match Set.contains id visited with
        | true -> (visited, result)
        | false ->
          match Map.tryFind id byId with
          | None -> (visited, result)
          | Some entry ->
            let visited' = Set.add id visited
            let (visited'', result') =
              entry.Dependencies
              |> List.filter (fun d -> Set.contains d allIds)
              |> List.fold (fun (v, r) dep -> visit v r dep) (visited', result)
            (visited'', entry :: result')
      let (_, sorted) =
        entries
        |> List.fold (fun (v, r) e -> visit v r e.CellId) (Set.empty, [])
      sorted |> List.rev

  /// Convert a CellGraph into ScribeEntries.
  let fromGraph (graph: CellGraph) : ScribeEntry list =
    graph.Cells
    |> Map.toList
    |> List.map (fun (_, cell) ->
      let deps =
        graph.Edges
        |> List.choose (fun (producer, consumer) ->
          match consumer = cell.Id with
          | true -> Some producer
          | false -> None)
        |> List.distinct
      { CellId = cell.Id
        Code = cell.Source
        Bindings = cell.Produces
        Dependencies = deps })

  /// Export entries as a clean .fsx script with topological ordering.
  let exportFsx (projectName: string) (entries: ScribeEntry list) : string =
    let sorted = entries |> dedup |> toposort
    let header =
      sprintf "(* @sagefs-scribe project:%s cells:%d *)\n(* Generated by SageFs Session Scribe *)\n" projectName sorted.Length
    let cellLines =
      sorted
      |> List.map (fun e ->
        let binds =
          match e.Bindings with
          | [] -> ""
          | bs -> sprintf " bindings:%s" (bs |> String.concat ",")
        let deps =
          match e.Dependencies with
          | [] -> ""
          | ds -> sprintf " deps:%s" (ds |> List.map string |> String.concat ",")
        sprintf "(* @sagefs-cell[%d]%s%s *)\n%s;;" e.CellId binds deps e.Code)
    header + "\n" + (cellLines |> String.concat "\n\n") + "\n"
