#!/usr/bin/env pwsh
# e2e-browser-fsharp.ps1 - Run the F# Playwright.NET dashboard journeys.
#
# Starts a freshly built SageFs daemon (isolated SAGEFS_DATA_DIR, non-default
# ports, --no-resume), generates the WebLive sample's startup profile, creates
# a session, waits for Ready, installs the Playwright Chromium browser for the
# .NET driver, then runs the [Integration] Dashboard browser tests from the
# Expecto suite against the dashboard.
#
# Exits 0 when all browser journeys pass, 1 otherwise.

param(
  [int]$McpPort = 37951,
  [int]$SessionWarmupSeconds = 120,
  [string]$SampleProject = "samples\demos\SageFs.Samples.WebappDatastar\SageFs.Samples.WebappDatastar.fsproj",
  [string]$Configuration = "Release",
  [string]$DiagnosticsDir = "e2e-browser-diagnostics"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$baseUrl = "http://localhost:$McpPort"
$dashboardUrl = "http://localhost:$($McpPort + 1)"
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$samplePath = [System.IO.Path]::GetFullPath((Join-Path $repoRoot $SampleProject))
$sampleProjectDir = Split-Path -Parent $samplePath
$diagnosticsRoot = [System.IO.Path]::GetFullPath((Join-Path $repoRoot $DiagnosticsDir))
$dataDir = Join-Path $diagnosticsRoot "sagefs-data"
$daemonStdoutPath = Join-Path $diagnosticsRoot "daemon-stdout.log"
$daemonStderrPath = Join-Path $diagnosticsRoot "daemon-stderr.log"
$daemonProcess = $null

function Section([string]$title) {
  Write-Host ""
  Write-Host "-- $title" -ForegroundColor Cyan
}

# -- 1. Start the daemon (isolated data dir, non-default ports, no resume) --
Section "1. Start daemon"
if (-not (Test-Path $diagnosticsRoot)) { New-Item -ItemType Directory -Force $diagnosticsRoot | Out-Null }
$env:SAGEFS_DATA_DIR = $dataDir
$env:SAGEFS_HOT_RELOAD = "true"
$daemonExe = Join-Path $repoRoot "SageFs\bin\$Configuration\net10.0\SageFs.exe"

$daemonProcess = Start-Process -FilePath $daemonExe `
  -ArgumentList "--mcp-port", $McpPort, "--no-resume" `
  -WorkingDirectory $repoRoot `
  -RedirectStandardOutput $daemonStdoutPath `
  -RedirectStandardError $daemonStderrPath `
  -PassThru

$reachable = $false
for ($i = 0; $i -lt 20; $i++) {
  Start-Sleep -Seconds 1
  try {
    Invoke-RestMethod -Method Get -Uri "$baseUrl/health" -TimeoutSec 2 -ErrorAction Stop | Out-Null
    $reachable = $true
    break
  } catch { }
}
if (-not $reachable) {
  Write-Host "X Daemon not reachable" -ForegroundColor Red
  if (Test-Path $daemonStderrPath) { Get-Content $daemonStderrPath -Tail 40 }
  exit 1
}
Write-Host "  OK Daemon healthy (data dir $dataDir)" -ForegroundColor Green

# -- 2. Generate the sample's startup profile (.SageFs/init.fsx) -----------
# A fresh checkout has no init profile (the .SageFs dir is gitignored), so a
# WebLive session would never start the sample app. The profile anchors the
# Falco app to this checkout's Release output and writes .SageFs/init-ok.txt
# once the app is listening.
Section "2. Sample startup profile"
$sampleSageFsDir = Join-Path $sampleProjectDir ".SageFs"
New-Item -ItemType Directory -Force $sampleSageFsDir | Out-Null
$initProfile = Join-Path $sampleSageFsDir "init.fsx"
$profileContent = @"
// SageFS startup profile (generated by scripts/e2e-browser-fsharp.ps1).
#I "bin/$Configuration/net10.0"
#r "Falco.dll"
#r "Falco.Markup.dll"
#r "Falco.Datastar.dll"
#r "StarFederation.Datastar.FSharp.dll"
#load "Program.fs"

open System
open System.IO
open System.Net.Http
open System.Threading.Tasks
open Microsoft.AspNetCore.Builder

try
  let sampleDir = Environment.CurrentDirectory
  let builder = WebApplication.CreateBuilder([||])
  builder.Environment.ContentRootPath <- sampleDir
  let app = builder.Build()
  SageFs.DevReloadInjector.injectMiddleware app (SageFs.DevReloadInjector.getWorkerPort ())
  app.UseRouting().UseFalco(SageFs.Samples.WebappDatastar.Program.routes) |> ignore

  let port =
    let listener = Net.Sockets.TcpListener(Net.IPAddress.Loopback, 0)
    listener.Start()
    let p = (listener.LocalEndpoint :?> Net.IPEndPoint).Port
    listener.Stop()
    p
  let baseUrl = sprintf "http://127.0.0.1:%d" port
  let runTask = Task.Run(fun () -> app.RunAsync(baseUrl))
  let mutable ok = false
  let deadline = DateTime.UtcNow.AddSeconds(15)
  use client = new HttpClient()
  while (not ok && DateTime.UtcNow < deadline) do
    try
      use _resp = client.GetAsync(sprintf "%s/todo/list" baseUrl).Result
      ok <- true
    with _ -> Task.Delay(200).Wait()
  if not ok then
    failwith (sprintf "Server did not start listening on %s within 15s" baseUrl)
  File.WriteAllText(
    Path.Combine(sampleDir, ".SageFs", "init-ok.txt"),
    sprintf "started at %s (runTask=%s)" baseUrl (string runTask.Status))
with ex ->
  let sampleDir = Environment.CurrentDirectory
  File.WriteAllText(
    Path.Combine(sampleDir, ".SageFs", "init-errors.txt"),
    sprintf "%s`n%s" ex.Message (ex.ToString()))
  reraise ()
"@
Set-Content -Path $initProfile -Value $profileContent -Encoding UTF8
Write-Host "  Generated $initProfile"

# -- 3. Create a WebLive session; wait for Ready ----------------------------
Section "3. Session warmup"
$sessionReady = $false
try {
  $createBody = @{
    projects = @($samplePath)
    workingDirectory = $sampleProjectDir
    workflow = "WebLive"
  } | ConvertTo-Json
  $createResp = Invoke-RestMethod -Method Post -Uri "$baseUrl/api/sessions/create" `
    -Body $createBody -ContentType "application/json" -TimeoutSec 15
  if ($createResp.success -ne $true) {
    Write-Host "X Session creation failed: $($createResp | ConvertTo-Json -Compress)" -ForegroundColor Red
  } else {
    Write-Host "  Session created; waiting for Ready (up to ${SessionWarmupSeconds}s)..."
    for ($i = 0; $i -lt $SessionWarmupSeconds; $i++) {
      Start-Sleep -Seconds 1
      try {
        $sessions = Invoke-RestMethod -Method Get -Uri "$baseUrl/api/sessions" -TimeoutSec 5
        $readySession = $sessions.sessions | Where-Object { $_.status -eq "Ready" } | Select-Object -First 1
        if ($readySession) {
          $sessionReady = $true
          Write-Host "  OK Session $($readySession.id) Ready after $($i + 1)s" -ForegroundColor Green
          break
        }
      } catch { }
    }
  }
} catch {
  Write-Host "X Session create failed: $_" -ForegroundColor Red
}
if (-not $sessionReady) {
  Write-Host "X Session never reached Ready" -ForegroundColor Red
  if (Test-Path $daemonStderrPath) { Get-Content $daemonStderrPath -Tail 40 }
  if ($daemonProcess -and -not $daemonProcess.HasExited) { Stop-Process -Id $daemonProcess.Id -Force }
  exit 1
}

# -- 4. Run the F# Playwright.NET dashboard journeys ------------------------
Section "4. F# Playwright.NET dashboard journeys"
$env:SAGEFS_DASHBOARD_PORT = "$($McpPort + 1)"
$testDll = Join-Path $repoRoot "SageFs.Tests\bin\$Configuration\net10.0\SageFs.Tests.dll"
if (-not (Test-Path $testDll)) {
  Write-Host "X Test DLL not found at $testDll (build SageFs.Tests first)" -ForegroundColor Red
  exit 1
}

$testExit = 0
try {
  & dotnet $testDll --integration --filter "Dashboard browser" --summary 2>&1 | Tee-Object -FilePath (Join-Path $diagnosticsRoot "browser-tests.log")
  $testExit = $LASTEXITCODE
} finally {
  if ($daemonProcess -and -not $daemonProcess.HasExited) {
    Stop-Process -Id $daemonProcess.Id -Force -ErrorAction SilentlyContinue
  }
  Remove-Item Env:SAGEFS_DATA_DIR -ErrorAction SilentlyContinue
  Remove-Item Env:SAGEFS_HOT_RELOAD -ErrorAction SilentlyContinue
  Remove-Item Env:SAGEFS_DASHBOARD_PORT -ErrorAction SilentlyContinue
}

if ($testExit -ne 0) {
  Write-Host "X Browser journeys failed (exit $testExit)" -ForegroundColor Red
  exit 1
}
Write-Host "  OK All F# dashboard browser journeys passed" -ForegroundColor Green
exit 0
