#!/usr/bin/env pwsh
# e2e-dashboard.ps1 - Real-browser dashboard journeys against a real daemon.
#
# Starts a freshly installed SageFs daemon (SAGEFS_DATA_DIR isolated to a temp
# dir, non-default port, --no-resume), creates a WebLive session on the Falco +
# Datastar sample project (so hot-reload is exercisable), waits for Ready, then
# runs the Playwright dashboard specs against the dashboard port.
#
# ASCII only (no checkmarks/box-drawing): Windows PowerShell 5.1 reads BOM-less
# .ps1 files as ANSI, which mangles non-ASCII bytes inside string literals and
# can break parsing.
#
# Exits 0 if all browser specs pass, 1 if any fail.

param(
  [int]$Port = 37951,
  [int]$DaemonTimeoutSeconds = 15,
  [int]$SessionWarmupSeconds = 120,
  [string]$SampleProject = "samples\demos\SageFs.Samples.WebappDatastar\SageFs.Samples.WebappDatastar.fsproj",
  [string]$Configuration = "Release",
  [string]$DiagnosticsDir = "e2e-diagnostics"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$baseUrl = "http://localhost:$Port"
$dashboardBaseUrl = "http://localhost:$($Port + 1)"
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$samplePath = [System.IO.Path]::GetFullPath((Join-Path $repoRoot $SampleProject))
$sampleProjectDir = Split-Path -Parent $samplePath
$diagnosticsRoot = [System.IO.Path]::GetFullPath((Join-Path $repoRoot $DiagnosticsDir))
$dataDir = Join-Path $diagnosticsRoot "sagefs-data"
$daemonStdoutPath = Join-Path $diagnosticsRoot "daemon-stdout.log"
$daemonStderrPath = Join-Path $diagnosticsRoot "daemon-stderr.log"
$playwrightReport = Join-Path $diagnosticsRoot "playwright-report"
$daemonProcess = $null
$sessionReady = $false
$playwrightExit = 1

function Section([string]$title) {
  Write-Host ""
  Write-Host "-- $title" -ForegroundColor Cyan
}

# -- 1. Start the daemon (isolated data dir, non-default port, no resume) -----
Section "1. Start daemon"
if (-not (Test-Path $diagnosticsRoot)) { New-Item -ItemType Directory -Force $diagnosticsRoot | Out-Null }
Remove-Item -Path $daemonStdoutPath, $daemonStderrPath -ErrorAction SilentlyContinue
$env:SAGEFS_DATA_DIR = $dataDir
$env:SAGEFS_HOT_RELOAD = "true"

$daemonProcess = Start-Process -FilePath "sagefs" `
  -ArgumentList "--mcp-port", $Port, "--no-resume" `
  -WorkingDirectory $repoRoot `
  -RedirectStandardOutput $daemonStdoutPath `
  -RedirectStandardError $daemonStderrPath `
  -PassThru

$reachable = $false
for ($i = 0; $i -lt $DaemonTimeoutSeconds; $i++) {
  Start-Sleep -Seconds 1
  try {
    $resp = Invoke-RestMethod -Method Get -Uri "$baseUrl/health" -TimeoutSec 2 -ErrorAction Stop
    # A bare daemon with no sessions reports healthy:false — any successful
    # HTTP response means the daemon is up and serving.
    $reachable = $true
    break
  } catch {
    # not up yet - keep polling
  }
}
if (-not $reachable) {
  Write-Host "  X Daemon not reachable after ${DaemonTimeoutSeconds}s" -ForegroundColor Red
  if (Test-Path $daemonStderrPath) { Get-Content $daemonStderrPath -Tail 40 }
  exit 1
}
Write-Host "  OK Daemon healthy (data dir $dataDir)" -ForegroundColor Green

# -- 1.5 Generate the sample's startup profile (.SageFs/init.fsx) -------------
# The .SageFs dir is gitignored (user-local session state), so a fresh CI
# checkout has no init profile and a WebLive session would never start the
# sample app. Generate one anchored to this checkout's build output. The FSI
# worker's CWD is the session working directory, and the worker process ALREADY
# has SageFs.Host loaded (DevReloadInjector is in-session) — the profile only
# needs the sample's own dependency DLLs from its bin dir.
Section "1.5 Sample startup profile"
$sampleSageFsDir = Join-Path $sampleProjectDir ".SageFs"
New-Item -ItemType Directory -Force $sampleSageFsDir | Out-Null
$initProfile = Join-Path $sampleSageFsDir "init.fsx"
$profileContent = @"
// SageFS startup profile (generated by scripts/e2e-dashboard.ps1 at run time).
// Starts the Falco todo app from SOURCE inside FSI so HotReloading can
// Harmony-detour re-evals onto the running app. Paths are literal and
// relative to the FSI worker's CWD (the sample project dir).
#I "bin/$Configuration/net10.0"
#r "Falco.dll"
#r "Falco.Markup.dll"
#r "Falco.Datastar.dll"
#r "StarFederation.Datastar.FSharp.dll"
#load "Program.fs"

open System
open System.IO
open System.Net.Http
open System.Threading.Tasks
open Microsoft.AspNetCore.Builder

try
  let sampleDir = Environment.CurrentDirectory
  let builder = WebApplication.CreateBuilder([||])
  builder.Environment.ContentRootPath <- sampleDir
  let app = builder.Build()
  SageFs.DevReloadInjector.injectMiddleware app (SageFs.DevReloadInjector.getWorkerPort ())
  app.UseRouting().UseFalco(SageFs.Samples.WebappDatastar.Program.routes) |> ignore

  // Pick a free port so restarted workers never collide on a fixed port.
  let port =
    let listener = Net.Sockets.TcpListener(Net.IPAddress.Loopback, 0)
    listener.Start()
    let p = (listener.LocalEndpoint :?> Net.IPEndPoint).Port
    listener.Stop()
    p
  let baseUrl = sprintf "http://127.0.0.1:%d" port
  let runTask = Task.Run(fun () -> app.RunAsync(baseUrl))
  let mutable ok = false
  let deadline = DateTime.UtcNow.AddSeconds(15)
  use client = new HttpClient()
  while (not ok && DateTime.UtcNow < deadline) do
    try
      use _resp = client.GetAsync(sprintf "%s/todo/list" baseUrl).Result
      ok <- true
    with _ -> Task.Delay(200).Wait()
  if not ok then
    failwith (sprintf "Server did not start listening on %s within 15s" baseUrl)
  File.WriteAllText(
    Path.Combine(sampleDir, ".SageFs", "init-ok.txt"),
    sprintf "started at %s (runTask=%s)" baseUrl (string runTask.Status))
with ex ->
  let sampleDir = Environment.CurrentDirectory
  File.WriteAllText(
    Path.Combine(sampleDir, ".SageFs", "init-errors.txt"),
    sprintf "%s`n%s" ex.Message (ex.ToString()))
  reraise ()
"@
Set-Content -Path $initProfile -Value $profileContent -Encoding UTF8
Write-Host "  Generated $initProfile"

# -- 2. Create a WebLive session on the sample project; wait Ready ------------
Section "2. Session warmup"
try {
  $createBody = @{
    projects = @($samplePath)
    workingDirectory = $sampleProjectDir
    workflow = "WebLive"
  } | ConvertTo-Json
  $createResp = Invoke-RestMethod -Method Post -Uri "$baseUrl/api/sessions/create" `
    -Body $createBody -ContentType "application/json" -TimeoutSec 15
  if ($createResp.success -ne $true) {
    Write-Host "  X Session creation failed: $($createResp | ConvertTo-Json -Compress)" -ForegroundColor Red
  } else {
    Write-Host "  Session created; waiting for Ready (up to ${SessionWarmupSeconds}s)..."
    for ($i = 0; $i -lt $SessionWarmupSeconds; $i++) {
      Start-Sleep -Seconds 1
      try {
        $sessions = Invoke-RestMethod -Method Get -Uri "$baseUrl/api/sessions" -TimeoutSec 5
        $readySession = $sessions.sessions | Where-Object { $_.status -eq "Ready" } | Select-Object -First 1
        if ($readySession) {
          $sessionReady = $true
          Write-Host "  OK Session $($readySession.id) Ready after $($i + 1)s" -ForegroundColor Green
          break
        }
        $all = @($sessions.sessions)
        if ($all.Count -gt 0 -and ($all | Where-Object { $_.status -ne "Faulted" }).Count -eq 0) {
          Write-Host "  X All sessions Faulted" -ForegroundColor Red
          break
        }
      } catch {
        # poll error - keep waiting
      }
    }
  }
} catch {
  Write-Host "  X Session create failed: $_" -ForegroundColor Red
}
if (-not $sessionReady) {
  Write-Host "  X Session never reached Ready" -ForegroundColor Red
  if (Test-Path $daemonStderrPath) { Get-Content $daemonStderrPath -Tail 40 }
  if ($daemonProcess -and -not $daemonProcess.HasExited) { Stop-Process -Id $daemonProcess.Id -Force }
  exit 1
}

# -- 3. Run the Playwright dashboard specs ------------------------------------
Section "3. Playwright dashboard specs"
$env:PLAYWRIGHT_BASE_URL = $dashboardBaseUrl
Push-Location $repoRoot
try {
  npx playwright test --reporter=list
  $playwrightExit = $LASTEXITCODE
} finally {
  Pop-Location
}

# -- 4. Diagnostics + cleanup --------------------------------------------------
if (Test-Path "$repoRoot\test-results") {
  Copy-Item -Path "$repoRoot\test-results" -Destination $playwrightReport -Recurse -Force -ErrorAction SilentlyContinue
}
if ($daemonProcess -and -not $daemonProcess.HasExited) {
  Stop-Process -Id $daemonProcess.Id -Force -ErrorAction SilentlyContinue
}
Remove-Item Env:SAGEFS_DATA_DIR -ErrorAction SilentlyContinue
Remove-Item Env:SAGEFS_HOT_RELOAD -ErrorAction SilentlyContinue

if ($playwrightExit -ne 0) {
  Write-Host "  X Playwright specs failed (exit $playwrightExit)" -ForegroundColor Red
  if (Test-Path $daemonStderrPath) { Get-Content $daemonStderrPath -Tail 60 }
  exit 1
}
Write-Host "  OK All dashboard E2E specs passed" -ForegroundColor Green
exit 0
